opr/opr/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using opr.Models;
using Microsoft.AspNet.Identity;
namespace opr.Controllers
{
    [Authorize]
    public class SchoolController : Controller
    {
        // GET: School
        public ActionResult Index()
        {
            Models.opr1Entities db = new opr1Entities();
            List<Models.School> model = new List<School>();
            model = db.Schools.ToList();
            return View(model);
            
        }

        public ActionResult EditSchool(int id)
        {

            Models.opr1Entities obj = new opr1Entities();
            ViewBag.modifiedBy = User.Identity.Name;
            var eid = obj.Schools.Where(w => w.Id == id).FirstOrDefault();
            if (obj == null)
            {
                return RedirectToAction("Index");
            }

            return View(eid);
         
        }
        [HttpPost]
        public ActionResult EditSchool(opr.Models.School schl)
        {
            Models.opr1Entities sub = new opr1Entities();          
            sub.Entry(schl).State = System.Data.Entity.EntityState.Modified;
            try
            {
                sub.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {

            }
            ModelState.AddModelError("", "Unable to save changes made to the entity.");
            return View(schl);

        }
    
     
        public ActionResult AddSchool()
        {
     
            ViewBag.ide = User.Identity.GetUserId();
            return View();
        }
        [HttpPost]
        public ActionResult AddSchool(opr.Models.School sch)
        {  
            Models.opr1Entities db = new opr1Entities();
            
            db.Schools.Add(sch);
            db.SaveChanges();
            return View();
        }
        public ActionResult Delete(int id)
        {
            Models.opr1Entities sub = new opr1Entities();
            School student_table = sub.Schools.Find(id);
            sub.Schools.Remove(student_table);
            sub.SaveChanges();
            return RedirectToAction("Index");
         
        }

    }
}

opr/opr/Views/School/AddSchool.cshtml
@model opr.Models.School
@{
    ViewBag.Title = "AddSchool";

}
<script src="~/Scripts/bootstrap.min.js"></script>
<h2>Add Schools</h2>
@using (Html.BeginForm())
{
<div class="container">
    <form action="" method="post">
        <div class="form-group row">

            <div class="col-xs-4">
                <label for="ex3">School Name:</label>
                @Html.TextBoxFor(model => model.SchoolName, new { required = "required", @class = "form-control", placeholder = "Enter School Name" })
            </div>
            <div class="col-xs-4">
                <label for="ex3">School Address:</label>
                @Html.TextBoxFor(model => model.Address, new { required = "required", @class = "form-control", placeholder = "Enter Address" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Contact Person name:</label>
                @Html.TextBoxFor(model => model.ContactPerson, new { required = "required", @class = "form-control", placeholder = "Enter Contact Name" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Email:</label>
                @Html.TextBoxFor(model => model.Email, new { required = "required", @class = "form-control", placeholder = "Enter Email" })

            </div>

            <div class="col-xs-4">

                <label for="ex3">Contact Name:</label>
                @Html.TextBoxFor(model => model.ContactPname, new { required = "required", @class = "form-control", placeholder = "Enter Email" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Contact Person Number:</label>
                @Html.TextBoxFor(model => model.ContactPnum, new { required = "required", @class = "form-control", placeholder = "Enter Contact Person Name" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Principal Name:</label>
                @Html.TextBoxFor(model => model.Principal, new { required = "required", @class = "form-control", placeholder = "Enter Principal Name" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Web Name:</label>
                @Html.TextBoxFor(model => model.Web, new { required = "required", @class = "form-control", placeholder = "Enter Web Site Name" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">phone Number:</label>
                @Html.TextBoxFor(model => model.Phone, new { required = "required", @class = "form-control", placeholder = "Enter Phone Number" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Short Code:</label>
                @Html.TextBoxFor(model => model.ShortCode, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })

            </div>
            <div class="col-xs-4">

                <label for="ex3">Description:</label>

                @Html.TextAreaFor(model => model.Description, new { required = "required", @class = "form-control", placeholder = "Enter Description" })

            </div>
            <div class="form-group">
                <label>
                      
                    @Html.HiddenFor(model => model.IsDeleted, new { @Vlaue = "1", required = "required", @class = "form-control", placeholder = "Enter Short Code" })
                </label>
            </div>
            <div class="form-group">
                <label>
                    @*<label for="email">IsActive:</label>*@
                    @Html.HiddenFor(model => model.IsActive, new {@Vlaue="0", required = "required", @class = "form-control", placeholder = "Enter Short Code" })
                </label>
            </div>

            <div class="form-group">
                <label>
                   @* <label for="email">Entery Date:</label>*@
                    @Html.HiddenFor(model => model.ModifiedDate, new { @Value = DateTime.Now.ToString("dd-MM-yyyy"), required = "required", @class = "form-control" })
                </label>
            </div>
            <div class="form-group">
                <label>
                    @*<label for="email">Modified By:</label>*@
                    @Html.HiddenFor(model => model.ModifiedBy, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })
                </label>
            </div>
            <div class="form-group">
                <label>
                    @*<label for="email">Modified Date:</label>*@
                    @Html.HiddenFor(model => model.ModifiedDate, new { required = "required", @class = "form-control"})
                </label>
            </div>
            <div class="form-group">
                <label>
                   @* <label for="email">User Id:</label>*@
                    @Html.HiddenFor(model => model.UserID, new {@Value=ViewBag.ide, required = "required", @class = "form-control", placeholder = "Enter Short Code" })
                </label>
            </div>
            <label><input type="submit" value="Submit" name="submit" /></label>
        </div>
    </form>
</div>
    @Html.ActionLink("Details Show", "Index", "School");
}

opr/opr/Views/School/EditSchool.cshtml
@model opr.Models.School
@{
    ViewBag.Title = "EditSchool";
}
<h2>AddSubject</h2>

@using (Html.BeginForm())
{
    <h2>Subject Info</h2>
    <p>@Html.ValidationSummary(true)</p>
    <form action="" method="post">
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <label>
                <label for="email">School Name:</label>
                @Html.TextBoxFor(model => model.SchoolName, new { required = "required", @class = "form-control", placeholder = "Enter School Name" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">School Address:</label>
                @Html.TextBoxFor(model => model.Address, new { required = "required", @class = "form-control", placeholder = "Enter Address" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Contact Person name:</label>
                @Html.TextBoxFor(model => model.ContactPerson, new { required = "required", @class = "form-control", placeholder = "Enter Contact Name" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Email:</label>
                @Html.TextBoxFor(model => model.Email, new { required = "required", @class = "form-control", placeholder = "Enter Email" })
            </label>
        </div>

        <div class="form-group">
            <label>
                <label for="email">Contact Name:</label>
                @Html.TextBoxFor(model => model.ContactPname, new { required = "required", @class = "form-control", placeholder = "Enter Email" })
            </label>
        </div>

        <div class="form-group">
            <label>
                <label for="email">Contact Person Number:</label>
                @Html.TextBoxFor(model => model.ContactPnum, new { required = "required", @class = "form-control", placeholder = "Enter Contact Person Name" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Principal Name:</label>
                @Html.TextBoxFor(model => model.Principal, new { required = "required", @class = "form-control", placeholder = "Enter Principal Name" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Web Name:</label>
                @Html.TextBoxFor(model => model.Web, new { required = "required", @class = "form-control", placeholder = "Enter Web Site Name" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">phone Number:</label>
                @Html.TextBoxFor(model => model.Phone, new { required = "required", @class = "form-control", placeholder = "Enter Phone Number" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Short Code:</label>
                @Html.TextBoxFor(model => model.ShortCode, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">Description:</label>

                @Html.TextAreaFor(model => model.Description, new { required = "required", @class = "form-control", placeholder = "Enter Description" })
            </label>
        </div>

        <div class="form-group">
            <label>
                <label for="email">Is Deleted:</label>
                @Html.TextBoxFor(model => model.IsDeleted, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })
            </label>
        </div>
        <div class="form-group">
            <label>
                <label for="email">IsActive:</label>
                @Html.TextBoxFor(model => model.IsActive, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })
            </label>
        </div>
        <div class="form-group">
            <label>
                @* <label for="email">User Id:</label>*@
                @Html.HiddenFor(model => model.UserID, new { required = "required", @class = "form-control", placeholder = "Enter Short Code" })
            </label>
        </div>


        <div class="form-group">
            <label>
                @*<label for="email">Entery Date:</label>*@
                @Html.HiddenFor(model => model.EnteryDate, new { @Value = DateTime.Now.ToString("dd-MM-yyyy"), required = "required", @class = "form-control" })
            </label>
        </div>
        <div class="form-group">
            <label>
                @* <label for="email">Modified By:</label>*@
                @Html.HiddenFor(model => model.ModifiedBy, new { @Value = @ViewBag.modifiedBy, required = "required", @class = "form-control", placeholder = "Enter Short Code" })
            </label>
        </div>
        <div class="form-group">
            <label>
                @* <label for="email">Modified Date:</label>*@
                @Html.HiddenFor(model => model.ModifiedDate, new { @Value = DateTime.Now.ToString("dd-MM-yyyy"), required = "required", @class = "form-control" })
            </label>
        </div>
        <input type="submit" value="Update Now" />
    </form>
}

opr/opr/Views/School/Index.cshtml
@model List<opr.Models.School>
@{
    ViewBag.Title = "Index";
}
<html>

<body>
    <h2>School Ini Details</h2>
    <div style="align-content:center">
        <input class="form-control" id="myInput" type="text" placeholder="Search..">
    </div>
    <div>
        <div>
            @Html.ActionLink("New Add", "AddSchool", "School");
        </div>
        <div>
            <table class="table table-dark table-striped ">
                <tr>
                    <th>ID</th>
                    <th>School Name</th>
                    <th>Address</th>
                    <th>Contact Person</th>
                    <th>Email</th>
                    <th>Contact Name</th>
                    <th>Contact Persionr</th>
                    <th>Principal</th>
                    <th>Web#</th>
                    <th>Phone</th>
                    <th>Short Code</th>
                    <th>Description</th>
                    <th>Is Deleted</th>
                    <th>Is Active</th>
                    <th>User Id</th>
                    <th>Entrey Date</th>
                    <th>Modify By</th>
                    <th>Modify Date</th>
                    <th>Action</th>

                </tr>
                @foreach (var std in Model)
                {

                    <tr>
                        <td>@std.Id</td>
                        <td>@std.SchoolName</td>
                        <td>@std.Address</td>
                        <td>@std.ContactPerson</td>
                        <td>@std.Email</td>
                        <td>@std.ContactPname</td>
                        <td>@std.ContactPnum</td>
                        <td>@std.Principal</td>
                        <td>@std.Web</td>
                        <td>@std.Phone</td>
                        <td>@std.ShortCode</td>
                        <td>@std.Description</td>
                        <td>@std.IsDeleted</td>
                        <td>@std.IsActive</td>
                        <td>@std.UserID</td>
                        <td>@std.EnteryDate</td>
                        <td>@std.ModifiedBy</td>
                        <td>@std.ModifiedDate</td>

                        <td>
                            @Html.ActionLink("Edit", "EditSchool", new { id = std.Id })|
                            @Html.ActionLink("Delete", "Delete", new { id = std.Id })|
                        </td>
                    </tr>

                }

            </table>

        </div>

    </div>
    <div>
        @Html.ActionLink("<<Go Back<<", "AddSchool", "School");
    </div>
</body>
</html>